# Generated by Django 3.2.7 on 2021-09-18 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrlist', '0002_auto_20210918_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='middle_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Отчество'),
        ),
    ]
