# Generated by Django 3.2.7 on 2021-09-19 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrlist', '0005_auto_20210918_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='divisions', to='hrlist.division', verbose_name='Подразделение'),
        ),
    ]
