# Generated by Django 3.2.7 on 2021-09-19 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrlist', '0006_staff_division'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='date_hire',
            field=models.DateField(blank=True, null=True, verbose_name='Дата приёма на работу'),
        ),
    ]
